### ISSUE TITLE
days or months between feature

### ISSUE THREAD

**Issue by chriskuz** [chriskuz/intro_to_python_project#6]
let's make a dynamic column where we calculate the difference between search and departure

**Comment by irenechau31** [comment]
DONE, -> CREATED 'daysleft' column, thinking whether to merge into main branch or copy/paste the code portion

**Comment by chriskuz** [comment]
Hey following up on this. You did this via merge right?

**Comment by chriskuz** [comment]
Actively working on bringing it to the production script and will use such to rebuild a newer cleaned df.
