### ISSUE TITLE
arrival time/departure time classification

### ISSUE THREAD

**Issue by chriskuz** [chriskuz/intro_to_python_project#7]
adding "night" "evening", etc for the specific times of arrival/evening

**Comment by chriskuz** [comment]
i think simple sum of these labels is fine (bar or whatever)

**Comment by irenechau31** [comment]
DONE, thinking whether I should merge it to the main branch or just copy/paste the code portion

**Comment by chriskuz** [comment]
Hey following up on this. You did this via merge right?
